#!/bin/sh
# This script disables fan control off NESPi+ case
# Dedicated to gollumer
# cyperghost for https://retropie.org.uk
# You need to install raspi-gpio with sudo apt install raspi-gpio
#
# GPIO 4 controls power
# place script to /lib/systemd/system-shutdown
# and make it executable with chmod +x shutdown_fan
# You need root for this

[[ $1 == "poweroff ]] && raspi-gpio set 4 op pn dl
